site_name: Quantum Trader Pro Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list

nav:
  - 'Home': index.md
  - 'Getting Started':
    - 'Introduction': getting-started/introduction.md
    - 'Quickstart': getting-started/quickstart.md
    - 'Tools & Resources': getting-started/tools_resources.md
  - 'Architecture':
    - 'System Overview': architecture/system_overview.md
    - 'Real-Time Data Flow': architecture/real_time_data_flow.md
    - 'AI Orchestration': architecture/ai_orchestration.md
  - 'Backend Services':
    - 'FastAPI Structure': backend/fastapi_structure.md
    - 'WebSocket Service': backend/websocket_service.md
    - 'Redis Pub/Sub': backend/redis_pubsub.md
  - 'API Reference':
    - 'Quantum Cipher API': api/quantum_cipher_api.md
    - 'Volume Profile API': api/quantum_volume_profile_api.md
  - 'AI & Signal Logic':
    - 'Indicator Definitions': ai-logic/indicator_definitions.md
    - 'Prompt Templates': ai-logic/prompt_templates.md
  - 'Deployment & Security':
    - 'Security Checklist': deployment/security_checklist.md
